unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# set CapsShift to Control via OS Keyboard Settings
set -g prefix C-s

set -g mouse on
set-window-option -g mode-keys vi

# Copy-Mode Bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Selektion sichtbar machen
set -g mode-style "fg=black,bg=yellow"

unbind h
unbind j
unbind k
unbind l

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-power'

set -g @tmux_power_theme 'everforest'
set -g @tmux_power_show_user false
set -g @tmux_power_show_host false
set -g @tmux_power_show_session true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
